os:
  - Visual Studio 2015

platform: x64
  - x64

branches:
  only:
    - master

install:
  - git submodule update --init --recursive
  - set PATH=C:\Program Files\CMake\bin;%PATH%

build:
  verbosity: detailed

configuration:
  - Debug
  
environment:
  matrix:
    - env_arch: "x64"
    - env_arch: "x86"

build_script:
  - mkdir build
  - cd build
  - if [%env_arch%]==[x64] (
      cmake .. -A x64 -DPE2SHC_BUILD_TESTING=ON )
  - if [%env_arch%]==[x86] (
      cmake .. -DPE2SHC_BUILD_TESTING=ON )
  - cmake --build . --target install
  - ctest -V
  - cd ..
  
